version: '3.8'

services:
  mysql_db:
    image: mysql:8
    restart: always
    container_name: mysql_container
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 0711
      MYSQL_DATABASE: sys
      MYSQL_PASSWORD: 0711
      MYSQL_USER: myRoot
    volumes:
      - ./dockerMySql:/var/lib/mysql/

  redis-server:
    image: redis:7.4
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./dockerRedis/data:/root/redis
      - ./dockerRedis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=0711
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
